server:
     port: 9081
     forward-headers-strategy: framework

spring:
     application:
          name: vg-ms-students
     data:
          mongodb:
               uri: mongodb+srv://sistemaSigei:t2eK0JR0YSwoT02e@sigei.oub8atq.mongodb.net/?retryWrites=true&w=majority&appName=SIGEI
               database: SIGEI
               auto-index-creation: false

# Configuración de SpringDoc OpenAPI (Swagger)
springdoc:
     api-docs:
          enabled: true
          path: /v3/api-docs
     swagger-ui:
          enabled: true
          path: /swagger-ui/index.html
          operations-sorter: method
          tags-sorter: alpha
          display-request-duration: true
          show-extensions: true
          show-common-extensions: true
     show-actuator: false

# Configuración de microservicios externos
microservices:
     institution:
          url: ${INSTITUTION_SERVICE_URL:http://localhost:9080/api/v1/institutions}
     classroom:
          url: ${CLASSROOM_SERVICE_URL:http://localhost:9080/api/v1/classrooms}
     user:
          url: ${USER_SERVICE_URL:http://localhost:9083/api/v1/users}
